## List Comprehension and Loops

In [2]:
vec = [[1,2,3], [4,5,6], [7,8,9]]
print([x for x in vec])
print([[y for y in x] for x in vec])
[num for elem in vec for num in elem]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
vec1 = []
for x in vec:
    for y in x:
        vec1.append(y)
print(vec1)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [4]:
[(x, y) for x in [1,2,3] for y in [3,1,4] if x != y]

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

In [5]:
combs = []
for x in [1,2,3]:
    for y in [3,1,4]:
        if x != y:
            combs.append((x, y))

combs

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

In [8]:
import numpy as np
y = np.arange(35).reshape(5,7)
print(y)
y[1:5:2,::3]

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


array([[ 7, 10, 13],
       [21, 24, 27]])

In [10]:
import numpy as np
y = np.arange(35).reshape(5,7)
print(y)
y[1:5:2,3]

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


array([10, 24])