# Numpy

In [2]:
import numpy as np

In [6]:
b = np.array([[0,1,2],[3,4,5]])
print(b[0, 0], b[0, 1], b[1, 0])
print(b)
print(b.shape)
print("Shape (# of [], # in []) # Multiple")

0 1 3
[[0 1 2]
 [3 4 5]]
(2, 3)
Shape (# of [], # in []) # Multiple


In [10]:
print(np.array([1,2,3,4,5]).shape)
print("# Shape (# in array, blank) # One Array")

(5,)
# Shape (# in array, blank) # One Array


\begin{align}
\dot{x} & = \sigma(y-x) \\
\dot{y} & = \rho x - y - xz \\
\dot{z} & = -\beta z + xy
\end{align}

This can be interpreted as 5 dimensions in the vector, since if the distance of the vector was takign with the Eucledian Distance Norm, then it would measure the distance in the five dimensions.

In [7]:
# Let numpy choose the datatype
x = np.array([0, 1])
y = np.array([2.0, 3.0])
# Force a particular datatype
z = np.array([5, 6], dtype=np.int64)
x.dtype, y.dtype, z.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [10]:
x = np.zeros((3,3), dtype=[('a', np.int32), ('b', np.float64, (3,3))])
print("x['a'].shape: ", x['a'].shape)
print("x['a'].dtype: ", x['a'].dtype)
print("x['b'].shape: ", x['b'].shape)
print("x['b'].dtype: ", x['b'].dtype)

x['a'].shape:  (3, 3)
x['a'].dtype:  int32
x['b'].shape:  (3, 3, 3, 3)
x['b'].dtype:  float64


In [11]:
a=np.array([[1,2], [3, 4], [5, 6]])
# Find the elements of a that are bigger than 2
print(a > 2)
# to get the actual value
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [27]:
print(a)
print(a[:1,0:3])

[[1 2]
 [3 4]
 [5 6]]
[[1 2]]


In [28]:
## Math

In [32]:
x=np.array([[1,2],[3,4],[5,6]])
y=np.array([[7,8],[9,10],[11,12]])
print(x+y)
print(np.add(x, y))

[[ 8 10]
 [12 14]
 [16 18]]
[[ 8 10]
 [12 14]
 [16 18]]


## Broadcasting
Broadcasting enables arithmetic operations to be performed between different shaped arrays. Let’s look at a simple example of adding a constant vector to each row of a matrix.

In [34]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

a=np.array([9,10])
b=np.array([11, 12])

# Inner product of vectors; both produce 219
print(a.dot(b))
print(np.dot(a, b))

219
219


In [35]:
# Compute outer product of vectors
# v has shape (3,)
v = np.array([1,2,3])
# w has shape (2,)
w = np.array([4,5])
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]
